spring:
  application:
    name: crawler

# cache 설정
  cache:
    type: ehcache

server:
  port: 8080

# taskExecutor
async-task:
  core-pool-size: 5
  max-pool-size: 20
  queue-capacity: 500

crawler:
  timeout: 10000 # 10sec
  redirection: true